# Infos
title: Agend'Arts
description: >-
  Intermetteurs de spectacle depuis 1996
email: agendartshorslesmurs@free.fr
address1: 4 rue Belfort
address2: 69004 Lyon
phone: 09 51 00 00 00
facebook_username: agendarts
wordpress_url: https://agendarts.wordpress.com/

# Routing
baseurl: ""
url: ""

# Build settings
future: true
markdown: kramdown
plugins: 
  # [jekyll-feed, jekyll-youtube]
 - jekyll-feed
  


# Collections
collections:
  months:
    output: true
    permalink: /:name/
  events:
    output: true
    permalink: /:collection/:year/:month/:day/:title
  members:
    output: false
  friends:
    output: false

# Defaults
defaults:
  - scope:
      path: ""
      type: months
    values:
      layout: "month"

keep_files:
  [assets/img/]

# exclude:
#   - _events/

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/